In [1]:
# Word Embedding Techniques using Embedding Layer in PyTorch

import torch
import torch.nn as nn
from torch.nn.utils.rnn import pad_sequence



In [2]:
# ---------------------------------------
# Input Sentences
# ---------------------------------------
sentences = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]


In [3]:

# ---------------------------------------
# Tokenizer (Manual Vocabulary Builder)
# ---------------------------------------
def build_vocab(sent_list):
    vocab = {"<PAD>": 0}
    idx = 1
    for sentence in sent_list:
        for word in sentence.lower().split():
            if word not in vocab:
                vocab[word] = idx
                idx += 1
    return vocab

vocab = build_vocab(sentences)
voc_size = len(vocab)
print("Vocabulary:", vocab)


Vocabulary: {'<PAD>': 0, 'the': 1, 'glass': 2, 'of': 3, 'milk': 4, 'juice': 5, 'cup': 6, 'tea': 7, 'i': 8, 'am': 9, 'a': 10, 'good': 11, 'boy': 12, 'developer': 13, 'understand': 14, 'meaning': 15, 'words': 16, 'your': 17, 'videos': 18, 'are': 19}


In [4]:

# ---------------------------------------
# Convert sentences → integer encoded
# ---------------------------------------
encoded_sentences = []
for s in sentences:
    encoded = [vocab[word] for word in s.lower().split()]
    encoded_sentences.append(torch.tensor(encoded))

print("\nInteger Encoded Sentences:")
for e in encoded_sentences:
    print(e)

# ---------------------------------------
# Padding using PyTorch
# ---------------------------------------
padded_sequences = pad_sequence(encoded_sentences, batch_first=True, padding_value=0)
print("\nPadded Sequences:")
print(padded_sequences)

# Length of sequence
sent_length = padded_sequences.size(1)

# ---------------------------------------
# PyTorch Embedding Layer
# ---------------------------------------
embedding_dim = 10

embedding = nn.Embedding(num_embeddings=voc_size, embedding_dim=embedding_dim)

# ---------------------------------------
# Get Embeddings
# ---------------------------------------
embedded_output = embedding(padded_sequences)

print("\nEmbedding Output Shape:", embedded_output.shape)
print("\nEmbedding Output for All Sentences:")
print(embedded_output)

print("\nEmbedding for First Sentence:")
print(embedded_output[0])



Integer Encoded Sentences:
tensor([1, 2, 3, 4])
tensor([1, 2, 3, 5])
tensor([1, 6, 3, 7])
tensor([ 8,  9, 10, 11, 12])
tensor([ 8,  9, 10, 11, 13])
tensor([14,  1, 15,  3, 16])
tensor([17, 18, 19, 11])

Padded Sequences:
tensor([[ 1,  2,  3,  4,  0],
        [ 1,  2,  3,  5,  0],
        [ 1,  6,  3,  7,  0],
        [ 8,  9, 10, 11, 12],
        [ 8,  9, 10, 11, 13],
        [14,  1, 15,  3, 16],
        [17, 18, 19, 11,  0]])

Embedding Output Shape: torch.Size([7, 5, 10])

Embedding Output for All Sentences:
tensor([[[-0.1964, -1.5979,  1.6137, -0.6783,  0.1248,  0.1648, -0.8254,
           1.9487, -0.4748, -0.9219],
         [-1.2968,  0.2790, -1.4750, -1.1369,  0.4360,  0.3531,  1.3146,
           0.6171, -1.1537,  1.3090],
         [ 0.5186, -1.1317,  0.2685, -1.4226,  1.0243, -1.8317,  0.9913,
           0.3826,  0.8265,  0.6821],
         [-1.1384,  0.8271, -0.9377,  1.1495,  1.1183,  0.0113, -1.1656,
           0.4588,  0.4064,  0.2806],
         [ 0.8519,  0.2758, -0.6109, -